package br.org.funcate.mobile.task;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.j256.ormlite.field.DatabaseField;

/**
 * 
 * Model
 * 
 * */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Task  implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	private Integer _id;
	@DatabaseField
	private Integer feature_code; // O idenfificador da feição (SSQQQNNNN),
	@DatabaseField
	private Integer id_address; // o código do logradouro
	@DatabaseField
	private String address_name; // nome do Logradouro
	@DatabaseField
	private Integer building_number; // numeração predial
	@DatabaseField
	private Integer latitude; // coordenadas do centroide da feição, no caso de Bauru o Lote.
	@DatabaseField
	private Integer longitude;
	@DatabaseField
	private Boolean isSyncronized; // sincronizado com o servidor?

	public Integer get_id() {
		return _id;
	}

	public void set_id(Integer _id) {
		this._id = _id;
	}

	public Integer getFeature_code() {
		return feature_code;
	}

	public void setFeature_code(Integer feature_code) {
		this.feature_code = feature_code;
	}
	
	public Integer getId_address() {
		return id_address;
	}

	public void setId_address(Integer id_address) {
		this.id_address = id_address;
	}

	public String getAddress_name() {
		return address_name;
	}

	public void setAddress_name(String address_name) {
		this.address_name = address_name;
	}

	public Integer getBuilding_number() {
		return building_number;
	}

	public void setBuilding_number(Integer building_number) {
		this.building_number = building_number;
	}

	public Integer getLatitude() {
		return latitude;
	}

	public void setLatitude(Integer latitude) {
		this.latitude = latitude;
	}

	public Integer getLongitude() {
		return longitude;
	}

	public void setLongitude(Integer longitude) {
		this.longitude = longitude;
	}

	public Boolean getIsSyncronized() {
		return isSyncronized;
	}

	public void setIsSyncronized(Boolean isSyncronized) {
		this.isSyncronized = isSyncronized;
	}

}